### ISSUE TITLE
"Cancel" returns [1,1,1]

### ISSUE THREAD

**Issue by VinhSonNguyen** [Smallpath/AdobeColorPicker#14]
When simply calling colorPicker(), then hitting "Cancel", the window returns white? Is this normal? I'd assume it would return null.

**Comment by smallpath** [comment]
Yes, If there is no input colour, it returns a default value [1,1,1].  

You can change the behavior to return null by modifying [Line #44](https://github.com/Smallpath/AdobeColorPicker/blob/master/colorPicker.js#L42) and [Line #55](https://github.com/Smallpath/AdobeColorPicker/blob/master/colorPicker.js#L55) to `null`
